### ISSUE TITLE
Unsupported Handler with SendDocument

### ISSUE THREAD

**Issue by BlackRose01** [maratik123/spring-telegram#6]
Hello there,

I want to send documents with a specific telegram command. But when I enter the command in telegram I get the following error in spring. Methods with SendMessage don't run into errors.

Best Regards,
BlackRose01

> 2019-02-22 09:31:19.049 ERROR 21028 --- [pool-1-thread-1] n.m.spring.telegram.TelegramBotService   : Unsupported handler 'TelegramHandler{bean=de.pagedesk.controller.TelegramController@1f641fb7, method=public org.telegram.telegrambots.meta.api.methods.send.SendDocument de.pagedesk.controller.TelegramController.getDocument(org.telegram.telegrambots.meta.api.objects.User) throws java.io.FileNotFoundException, telegramCommand=@name.maratik.spring.telegram.annotation.TelegramCommand(value=[/sola], description=Testmethode, isHelp=false, commands=[/sola], hidden=false)}'

`
@TelegramCommand(value = "/sola", description = "Testmethode")
public SendDocument getDocument(User user) throws FileNotFoundException {
    System.out.println("moni");
    FileInputStream fis = new FileInputStream(new File("<DocumentPath>"));
    SendDocument sendDocumentRequest = new SendDocument();

sendDocumentRequest.setChatId(user.getId().longValue());
    sendDocumentRequest.setDocument("Testdokument", fis);
    sendDocumentRequest.setCaption("Test");
    //sendDocument(sendDocumentRequest);

return sendDocumentRequest;
    //return new SendDocument().setChatId(user.getId().toString()).setDocument("Testdokument", fis).setCaption("Test");
    //return new SendDocument().setChatId(user.getId().longValue()).setNewDocument(new File("<DocumentPath>").getAbsoluteFile());
}
`

**Comment by maratik123** [comment]
Already answered in maratik123/spring-telegram-example#4
